services:
  # Servicio de la aplicaci√≥n Node.js ( Backend )
  backend:
    container_name: ${BACKEND_CONTAINER_NAME}
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "${BACKEND_LOCAL}:${BACKEND_PORT}"
    volumes:
      - ./app-backend:/usr/src/backend/app-backend
      - ./.env:/usr/src/backend/.env
      - /usr/src/backend/node_modules
    env_file:
      - ./.env
    environment:
      - NODE_ENV=${NODE_ENV}
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:${POSTGRES_PORT}/${POSTGRES_DB}
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: "${BACKEND_CPU_LIMIT}"
          memory: ${BACKEND_MEMORY_LIMIT}
    networks:
      - backend

  frontend:
    container_name: ${FRONTEND_CONTAINER_NAME}
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "${FRONTEND_LOCAL}:${FRONTEND_PORT}"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://backend:${BACKEND_PORT}
    volumes:
      - ./frontend:/usr/src/app
      - ./.env:/usr/src/frontend/.env
      - /usr/src/app/node_modules
    env_file:
      - ./.env
    deploy:
      resources:
        limits:
          cpus: "${FRONTEND_CPU_LIMIT}"
          memory: ${FRONTEND_MEMORY_LIMIT}
    networks:
      - backend
  # Servicio de la base de datos PostgreSQL
  db:
    image: postgres:15-alpine
    ports:
      - "${POSTGRES_LOCAL}:${POSTGRES_PORT}"
    container_name: ${DB_CONTAINER_NAME}
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          cpus: "${DB_CPU_LIMIT}"
          memory: ${DB_MEMORY_LIMIT}
    networks:
      - backend

volumes:
  db_data:

networks:
  backend:
    driver: bridge
